PRO-2685: Add google translate widget
civis-vote/civis-frontend pull request #410
Opened 2024-01-04 15:03 UTC by sehgxl

What does the pr do?
- Adds google translate widget.

Concerns : 
- This [guide](https://docs.google.com/document/d/12umeKgbOzmLEgm2PitGM-MBAEtycJVhNFkoreXjb4DY/edit) was shared by the the client. According to this the API key gets exposed. 

Screenshots
![image](https://github.com/civis-vote/civis-frontend/assets/83122406/a681d6cb-c943-41c5-ae56-ebe54f47177b)

2024-01-04 15:14 UTC, mikevic reviewed
@sehgxl - we should talk to Karan or the client on where they want the widget to be placed?

2024-01-04 16:56 UTC, gpalsingh requested changes

2024-01-04 16:56 UTC, gpalsingh commented on src/index.html
> +    console.log("google script ran");
Remove console logs

2024-01-05 12:33 UTC, gpalsingh approved these changes

2024-01-12 11:40 UTC, gpalsingh requested changes
Since the issue was related to CSP, can we move back the code to `index.html`?

2024-01-19 07:35 UTC, sehgxl commented
> Since the issue was related to CSP, can we move back the code to `index.html`?

I tried doing that. It does not work when deployed. So again I am adding the tag dynamically.

2024-01-19 12:38 UTC, gpalsingh commented on src/index.html
> -  <script src="https://cdn.ckeditor.com/4.6.1/full/ckeditor.js"></script>
Why is this being removed?

2024-01-30 18:19 UTC, gpalsingh commented on src/index.html
> -  <script src="https://cdn.ckeditor.com/4.6.1/full/ckeditor.js"></script>
@sehgxl

2024-07-01 07:02 UTC, closed without merging